name: 'NPM Build and Deploy'
description: 'Build NPM projects and deploys them to Artifactory'

inputs:
  version:
    description: 'Build version'
    required: false
  deployer:
    description: 'Build deployer'
    required: false
  resolver:
    description: 'Build resolver'
    required: false
  build_name:
    description: 'Build name'
    required: false
  build_number:
    description: 'Build number'
    required: false
  server_id:
    description: 'Server ID'
    required: false
  rt_url:
    description: 'Artifactory URL'
    required: false
  rt_access_token:
    description: 'Artifactory access token'
    required: false
  user:
    description: 'User name'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Build Pre Requisites
      run: build_pre_req.sh
      shell: bash

    - name: Configure NPM
      #run: npm_builder.sh ${{ inputs.version }} ${{ inputs.resolver }}
      run: |
        source npm_builder.sh
        configure_npm_yml ${{ inputs.version }} ${{ inputs.resolver }} ${{ inputs.deployer }}
        install_npm_package ${{ inputs.build_name }} ${{ inputs.build_number }}
        configure_jfrog_server ${{ inputs.server_id }} ${{ inputs.rt_url }} ${{ inputs.rt_access_token }} ${{ inputs.user }}
      shell: bash