name: 'NPM Build and Deploy'
description: 'Build NPM projects and deploys them to Artifactory'

inputs:
  deployer:
    description: 'Build deployer'
    required: false
  resolver:
    description: 'Build resolver'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set deployer
      run: |
        echo "Deployer - $DEPLOYER"
        echo "Resolver - $RESOLVER"
      shell: bash
      env:
        DEPLOYER: ${{ inputs.deployer }}
        RESOLVER: ${{ inputs.Resolver }}

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Setup up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ secrets.ARTIFACTORY_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

    - name: Create NPM Configurations
      run: npm_builder.sh
      shell: bash